## Obtener lista de ciclistas
GET http://localhost:8090/api/v1/ciclistas
Content-Type: application/json

###

## Obtener ciclistas ordenados de forma descendente
GET http://localhost:8090/api/v1/ciclistas/orden/desc
Content-Type: application/json

###

## Obtener ciclista por ID
GET http://localhost:8090/api/v1/ciclistas/1/info
Content-Type: application/json

###

## Obtener ciclistas ordenados por nombre de forma descendente
GET http://localhost:8090/api/v1/ciclistas/nombre/M/orden/desc
Content-Type: application/json

###

## Crear un nuevo ciclista
POST http://localhost:8090/api/v1/ciclistas
Content-Type: application/json

{
  "nombre": "Joan Benavent",
  "nacion": "España",
  "fechaNacimiento": "1995-07-20"
}

###

## Editar un ciclista
PUT http://localhost:8090/api/v1/ciclistas/1
Content-Type: application/json

{
  "nombre": "Alejandro Valverde",
  "nacion": "España",
  "fechaNacimiento": "1980-04-25"
}

###

## Eliminar ciclista por ID
DELETE http://localhost:8090/api/v1/ciclistas/1
Content-Type: application/json

###