## Obtener lista de equipos
GET http://localhost:8090/api/v1/equipos
Content-Type: application/json

###

## Obtener equipos ordenados de forma descendente
GET http://localhost:8090/api/v1/equipos/orden/desc
Content-Type: application/json

###

## Obtener equipo por ID
GET http://localhost:8090/api/v1/equipos/1/info
Content-Type: application/json

###

## Obtener equipos ordenados por nombre de forma descendente
GET http://localhost:8090/api/v1/equipos/nombre/E/orden/desc
Content-Type: application/json

###

## Crear un nuevo equipo
POST http://localhost:8090/api/v1/equipos
Content-Type: application/json

{
  "nombre": "BENAVENTES",
  "nacion": "España",
  "director": "Joan Benavent"
}

###

## Editar un equipo
PUT http://localhost:8090/api/v1/equipos/1
Content-Type: application/json

{
  "nombre": "BENAVENTES",
  "nacion": "España",
  "director": "Joan Benavent"
}

###

## Eliminar equipo por ID
DELETE http://localhost:8090/api/v1/equipos/1
Content-Type: application/json

###